# Generated by Django 4.2.9 on 2024-05-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='BuyerEmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='PurchaseDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
